// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Enums.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Protos/Enums.proto</summary>
public static partial class EnumsReflection {

  #region Descriptor
  /// <summary>File descriptor for Protos/Enums.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EnumsReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJQcm90b3MvRW51bXMucHJvdG8qJQoKU3RhdHVzRW51bRILCgdQYXNzaXZl",
          "EAASCgoGQWN0aXZlEAEqbAoPU3BhY2VTeXN0ZW1FbnVtEgkKBU5hYm9vEAAS",
          "DAoIQWxkZXJhYW4QARIJCgVFbmRvchACEggKBEhvdGgQAxIJCgVKYWtrdRAE",
          "EhIKDlN0YXJraWxsZXJCYXNlEAUSDAoIVGF0b29pbmUQBionCglBbGVydEVu",
          "dW0SCgoGTm9ybWFsEAASDgoKRW5lbXlBdGFjaxABKi4KCk9iamVjdEVudW0S",
          "CwoHVW5rbm93bhAAEggKBEFsbHkQARIJCgVFbmVteRACKjAKDk9iamVjdFNp",
          "emVFbnVtEgkKBVNtYWxsEAASCgoGTWVkaXVtEAESBwoDQmlnEAJiBnByb3Rv",
          "Mw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::StatusEnum), typeof(global::SpaceSystemEnum), typeof(global::AlertEnum), typeof(global::ObjectEnum), typeof(global::ObjectSizeEnum), }, null));
  }
  #endregion

}
#region Enums
public enum StatusEnum {
  [pbr::OriginalName("Passive")] Passive = 0,
  [pbr::OriginalName("Active")] Active = 1,
}

public enum SpaceSystemEnum {
  [pbr::OriginalName("Naboo")] Naboo = 0,
  [pbr::OriginalName("Alderaan")] Alderaan = 1,
  [pbr::OriginalName("Endor")] Endor = 2,
  [pbr::OriginalName("Hoth")] Hoth = 3,
  [pbr::OriginalName("Jakku")] Jakku = 4,
  [pbr::OriginalName("StarkillerBase")] StarkillerBase = 5,
  [pbr::OriginalName("Tatooine")] Tatooine = 6,
}

public enum AlertEnum {
  [pbr::OriginalName("Normal")] Normal = 0,
  [pbr::OriginalName("EnemyAtack")] EnemyAtack = 1,
}

public enum ObjectEnum {
  [pbr::OriginalName("Unknown")] Unknown = 0,
  [pbr::OriginalName("Ally")] Ally = 1,
  [pbr::OriginalName("Enemy")] Enemy = 2,
}

public enum ObjectSizeEnum {
  [pbr::OriginalName("Small")] Small = 0,
  [pbr::OriginalName("Medium")] Medium = 1,
  [pbr::OriginalName("Big")] Big = 2,
}

#endregion


#endregion Designer generated code
