// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/StarWarsContract.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace StartWarsContract {

  /// <summary>Holder for reflection information generated from Protos/StarWarsContract.proto</summary>
  public static partial class StarWarsContractReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/StarWarsContract.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StarWarsContractReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1Qcm90b3MvU3RhcldhcnNDb250cmFjdC5wcm90bxIRc3RhcnRXYXJzQ29u",
            "dHJhY3QaElByb3Rvcy9FbnVtcy5wcm90byI4ChVPcGVuTGlnaHRTcGVlZFJl",
            "cXVlc3QSEAoIRGlzdGFuY2UYASABKAESDQoFUG93ZXIYAiABKAMiNQoWT3Bl",
            "bkxpZ2h0U3BlZWRSZXNwb25zZRIbCgZTdGF0dXMYASABKA4yCy5TdGF0dXNF",
            "bnVtIl4KEkF1dG9Db250cm9sUmVxdWVzdBIbCgZTdGF0dXMYASABKA4yCy5T",
            "dGF0dXNFbnVtEisKEURlc3RpbmF0aW9uU3lzdGVtGAIgASgOMhAuU3BhY2VT",
            "eXN0ZW1FbnVtIjYKE0F1dG9Db250cm9sUmVzcG9uc2USDQoFU3BlZWQYASAB",
            "KAESEAoIRGlzdGFuY2UYAiABKAEidAoYT3BlblJhZGFyU2Nhbm5pbmdSZXF1",
            "ZXN0EiMKCk9iamVjdFNpemUYASABKA4yDy5PYmplY3RTaXplRW51bRIQCghE",
            "aXN0YW5jZRgCIAEoARIhCgxPYmplY3RTdGF0dXMYAyABKA4yCy5PYmplY3RF",
            "bnVtIjYKGU9wZW5SYWRhclNjYW5uaW5nUmVzcG9uc2USGQoFQWxlcnQYASAB",
            "KA4yCi5BbGVydEVudW0iSAoTUmFkaW9Db250cm9sUmVxdWVzdBIgCgZTeXN0",
            "ZW0YASABKA4yEC5TcGFjZVN5c3RlbUVudW0SDwoHTWVzc2FnZRgCIAEoCSJJ",
            "ChRSYWRpb0NvbnRyb2xSZXNwb25zZRIgCgZTeXN0ZW0YASABKA4yEC5TcGFj",
            "ZVN5c3RlbUVudW0SDwoHTWVzc2FnZRgCIAEoCTK/AwoXTWlsbGVubml1bUZh",
            "bGNvblNlcnZpY2USZwoOT3BlbkxpZ2h0U3BlZWQSKC5zdGFydFdhcnNDb250",
            "cmFjdC5PcGVuTGlnaHRTcGVlZFJlcXVlc3QaKS5zdGFydFdhcnNDb250cmFj",
            "dC5PcGVuTGlnaHRTcGVlZFJlc3BvbnNlIgASYAoLQXV0b0NvbnRyb2wSJS5z",
            "dGFydFdhcnNDb250cmFjdC5BdXRvQ29udHJvbFJlcXVlc3QaJi5zdGFydFdh",
            "cnNDb250cmFjdC5BdXRvQ29udHJvbFJlc3BvbnNlIgAwARJyChFPcGVuUmFk",
            "YXJTY2FubmluZxIrLnN0YXJ0V2Fyc0NvbnRyYWN0Lk9wZW5SYWRhclNjYW5u",
            "aW5nUmVxdWVzdBosLnN0YXJ0V2Fyc0NvbnRyYWN0Lk9wZW5SYWRhclNjYW5u",
            "aW5nUmVzcG9uc2UiACgBEmUKDFJhZGlvQ29udHJvbBImLnN0YXJ0V2Fyc0Nv",
            "bnRyYWN0LlJhZGlvQ29udHJvbFJlcXVlc3QaJy5zdGFydFdhcnNDb250cmFj",
            "dC5SYWRpb0NvbnRyb2xSZXNwb25zZSIAKAEwAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EnumsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::StartWarsContract.OpenLightSpeedRequest), global::StartWarsContract.OpenLightSpeedRequest.Parser, new[]{ "Distance", "Power" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StartWarsContract.OpenLightSpeedResponse), global::StartWarsContract.OpenLightSpeedResponse.Parser, new[]{ "Status" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StartWarsContract.AutoControlRequest), global::StartWarsContract.AutoControlRequest.Parser, new[]{ "Status", "DestinationSystem" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StartWarsContract.AutoControlResponse), global::StartWarsContract.AutoControlResponse.Parser, new[]{ "Speed", "Distance" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StartWarsContract.OpenRadarScanningRequest), global::StartWarsContract.OpenRadarScanningRequest.Parser, new[]{ "ObjectSize", "Distance", "ObjectStatus" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StartWarsContract.OpenRadarScanningResponse), global::StartWarsContract.OpenRadarScanningResponse.Parser, new[]{ "Alert" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StartWarsContract.RadioControlRequest), global::StartWarsContract.RadioControlRequest.Parser, new[]{ "System", "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StartWarsContract.RadioControlResponse), global::StartWarsContract.RadioControlResponse.Parser, new[]{ "System", "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OpenLightSpeedRequest : pb::IMessage<OpenLightSpeedRequest> {
    private static readonly pb::MessageParser<OpenLightSpeedRequest> _parser = new pb::MessageParser<OpenLightSpeedRequest>(() => new OpenLightSpeedRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OpenLightSpeedRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StartWarsContract.StarWarsContractReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenLightSpeedRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenLightSpeedRequest(OpenLightSpeedRequest other) : this() {
      distance_ = other.distance_;
      power_ = other.power_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenLightSpeedRequest Clone() {
      return new OpenLightSpeedRequest(this);
    }

    /// <summary>Field number for the "Distance" field.</summary>
    public const int DistanceFieldNumber = 1;
    private double distance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    /// <summary>Field number for the "Power" field.</summary>
    public const int PowerFieldNumber = 2;
    private long power_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Power {
      get { return power_; }
      set {
        power_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OpenLightSpeedRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OpenLightSpeedRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Distance, other.Distance)) return false;
      if (Power != other.Power) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Distance != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Distance);
      if (Power != 0L) hash ^= Power.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Distance != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Distance);
      }
      if (Power != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Power);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Distance != 0D) {
        size += 1 + 8;
      }
      if (Power != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Power);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OpenLightSpeedRequest other) {
      if (other == null) {
        return;
      }
      if (other.Distance != 0D) {
        Distance = other.Distance;
      }
      if (other.Power != 0L) {
        Power = other.Power;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Distance = input.ReadDouble();
            break;
          }
          case 16: {
            Power = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class OpenLightSpeedResponse : pb::IMessage<OpenLightSpeedResponse> {
    private static readonly pb::MessageParser<OpenLightSpeedResponse> _parser = new pb::MessageParser<OpenLightSpeedResponse>(() => new OpenLightSpeedResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OpenLightSpeedResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StartWarsContract.StarWarsContractReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenLightSpeedResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenLightSpeedResponse(OpenLightSpeedResponse other) : this() {
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenLightSpeedResponse Clone() {
      return new OpenLightSpeedResponse(this);
    }

    /// <summary>Field number for the "Status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::StatusEnum status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::StatusEnum Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OpenLightSpeedResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OpenLightSpeedResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != 0) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OpenLightSpeedResponse other) {
      if (other == null) {
        return;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::StatusEnum) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class AutoControlRequest : pb::IMessage<AutoControlRequest> {
    private static readonly pb::MessageParser<AutoControlRequest> _parser = new pb::MessageParser<AutoControlRequest>(() => new AutoControlRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AutoControlRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StartWarsContract.StarWarsContractReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AutoControlRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AutoControlRequest(AutoControlRequest other) : this() {
      status_ = other.status_;
      destinationSystem_ = other.destinationSystem_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AutoControlRequest Clone() {
      return new AutoControlRequest(this);
    }

    /// <summary>Field number for the "Status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::StatusEnum status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::StatusEnum Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "DestinationSystem" field.</summary>
    public const int DestinationSystemFieldNumber = 2;
    private global::SpaceSystemEnum destinationSystem_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SpaceSystemEnum DestinationSystem {
      get { return destinationSystem_; }
      set {
        destinationSystem_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AutoControlRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AutoControlRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (DestinationSystem != other.DestinationSystem) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != 0) hash ^= Status.GetHashCode();
      if (DestinationSystem != 0) hash ^= DestinationSystem.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Status != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (DestinationSystem != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) DestinationSystem);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (DestinationSystem != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DestinationSystem);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AutoControlRequest other) {
      if (other == null) {
        return;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.DestinationSystem != 0) {
        DestinationSystem = other.DestinationSystem;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::StatusEnum) input.ReadEnum();
            break;
          }
          case 16: {
            DestinationSystem = (global::SpaceSystemEnum) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class AutoControlResponse : pb::IMessage<AutoControlResponse> {
    private static readonly pb::MessageParser<AutoControlResponse> _parser = new pb::MessageParser<AutoControlResponse>(() => new AutoControlResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AutoControlResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StartWarsContract.StarWarsContractReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AutoControlResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AutoControlResponse(AutoControlResponse other) : this() {
      speed_ = other.speed_;
      distance_ = other.distance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AutoControlResponse Clone() {
      return new AutoControlResponse(this);
    }

    /// <summary>Field number for the "Speed" field.</summary>
    public const int SpeedFieldNumber = 1;
    private double speed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Speed {
      get { return speed_; }
      set {
        speed_ = value;
      }
    }

    /// <summary>Field number for the "Distance" field.</summary>
    public const int DistanceFieldNumber = 2;
    private double distance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AutoControlResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AutoControlResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Speed, other.Speed)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Distance, other.Distance)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Speed != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Speed);
      if (Distance != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Distance);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Speed != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Speed);
      }
      if (Distance != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Distance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Speed != 0D) {
        size += 1 + 8;
      }
      if (Distance != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AutoControlResponse other) {
      if (other == null) {
        return;
      }
      if (other.Speed != 0D) {
        Speed = other.Speed;
      }
      if (other.Distance != 0D) {
        Distance = other.Distance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Speed = input.ReadDouble();
            break;
          }
          case 17: {
            Distance = input.ReadDouble();
            break;
          }
        }
      }
    }

  }

  public sealed partial class OpenRadarScanningRequest : pb::IMessage<OpenRadarScanningRequest> {
    private static readonly pb::MessageParser<OpenRadarScanningRequest> _parser = new pb::MessageParser<OpenRadarScanningRequest>(() => new OpenRadarScanningRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OpenRadarScanningRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StartWarsContract.StarWarsContractReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenRadarScanningRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenRadarScanningRequest(OpenRadarScanningRequest other) : this() {
      objectSize_ = other.objectSize_;
      distance_ = other.distance_;
      objectStatus_ = other.objectStatus_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenRadarScanningRequest Clone() {
      return new OpenRadarScanningRequest(this);
    }

    /// <summary>Field number for the "ObjectSize" field.</summary>
    public const int ObjectSizeFieldNumber = 1;
    private global::ObjectSizeEnum objectSize_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ObjectSizeEnum ObjectSize {
      get { return objectSize_; }
      set {
        objectSize_ = value;
      }
    }

    /// <summary>Field number for the "Distance" field.</summary>
    public const int DistanceFieldNumber = 2;
    private double distance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    /// <summary>Field number for the "ObjectStatus" field.</summary>
    public const int ObjectStatusFieldNumber = 3;
    private global::ObjectEnum objectStatus_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ObjectEnum ObjectStatus {
      get { return objectStatus_; }
      set {
        objectStatus_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OpenRadarScanningRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OpenRadarScanningRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ObjectSize != other.ObjectSize) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Distance, other.Distance)) return false;
      if (ObjectStatus != other.ObjectStatus) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ObjectSize != 0) hash ^= ObjectSize.GetHashCode();
      if (Distance != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Distance);
      if (ObjectStatus != 0) hash ^= ObjectStatus.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ObjectSize != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ObjectSize);
      }
      if (Distance != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Distance);
      }
      if (ObjectStatus != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ObjectStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ObjectSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ObjectSize);
      }
      if (Distance != 0D) {
        size += 1 + 8;
      }
      if (ObjectStatus != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ObjectStatus);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OpenRadarScanningRequest other) {
      if (other == null) {
        return;
      }
      if (other.ObjectSize != 0) {
        ObjectSize = other.ObjectSize;
      }
      if (other.Distance != 0D) {
        Distance = other.Distance;
      }
      if (other.ObjectStatus != 0) {
        ObjectStatus = other.ObjectStatus;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ObjectSize = (global::ObjectSizeEnum) input.ReadEnum();
            break;
          }
          case 17: {
            Distance = input.ReadDouble();
            break;
          }
          case 24: {
            ObjectStatus = (global::ObjectEnum) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class OpenRadarScanningResponse : pb::IMessage<OpenRadarScanningResponse> {
    private static readonly pb::MessageParser<OpenRadarScanningResponse> _parser = new pb::MessageParser<OpenRadarScanningResponse>(() => new OpenRadarScanningResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OpenRadarScanningResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StartWarsContract.StarWarsContractReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenRadarScanningResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenRadarScanningResponse(OpenRadarScanningResponse other) : this() {
      alert_ = other.alert_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OpenRadarScanningResponse Clone() {
      return new OpenRadarScanningResponse(this);
    }

    /// <summary>Field number for the "Alert" field.</summary>
    public const int AlertFieldNumber = 1;
    private global::AlertEnum alert_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AlertEnum Alert {
      get { return alert_; }
      set {
        alert_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OpenRadarScanningResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OpenRadarScanningResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Alert != other.Alert) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Alert != 0) hash ^= Alert.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Alert != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Alert);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Alert != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Alert);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OpenRadarScanningResponse other) {
      if (other == null) {
        return;
      }
      if (other.Alert != 0) {
        Alert = other.Alert;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Alert = (global::AlertEnum) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RadioControlRequest : pb::IMessage<RadioControlRequest> {
    private static readonly pb::MessageParser<RadioControlRequest> _parser = new pb::MessageParser<RadioControlRequest>(() => new RadioControlRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RadioControlRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StartWarsContract.StarWarsContractReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RadioControlRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RadioControlRequest(RadioControlRequest other) : this() {
      system_ = other.system_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RadioControlRequest Clone() {
      return new RadioControlRequest(this);
    }

    /// <summary>Field number for the "System" field.</summary>
    public const int SystemFieldNumber = 1;
    private global::SpaceSystemEnum system_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SpaceSystemEnum System {
      get { return system_; }
      set {
        system_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RadioControlRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RadioControlRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (System != other.System) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (System != 0) hash ^= System.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (System != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) System);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (System != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) System);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RadioControlRequest other) {
      if (other == null) {
        return;
      }
      if (other.System != 0) {
        System = other.System;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            System = (global::SpaceSystemEnum) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RadioControlResponse : pb::IMessage<RadioControlResponse> {
    private static readonly pb::MessageParser<RadioControlResponse> _parser = new pb::MessageParser<RadioControlResponse>(() => new RadioControlResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RadioControlResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StartWarsContract.StarWarsContractReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RadioControlResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RadioControlResponse(RadioControlResponse other) : this() {
      system_ = other.system_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RadioControlResponse Clone() {
      return new RadioControlResponse(this);
    }

    /// <summary>Field number for the "System" field.</summary>
    public const int SystemFieldNumber = 1;
    private global::SpaceSystemEnum system_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SpaceSystemEnum System {
      get { return system_; }
      set {
        system_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RadioControlResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RadioControlResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (System != other.System) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (System != 0) hash ^= System.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (System != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) System);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (System != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) System);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RadioControlResponse other) {
      if (other == null) {
        return;
      }
      if (other.System != 0) {
        System = other.System;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            System = (global::SpaceSystemEnum) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
